#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_cake_list:
    path:     /cakes
    controller: App\Controller\CakeController::list

app_cake_show:
    path: /cakes/{cakeId}
    controller: App\Controller\CakeController::show
    requirements:
        cakeId: '\d+'

app_cake_create:
    path: /cakes/create
    controller: App\Controller\CakeController::create
